import assert from 'node:assert/strict';
import ts from 'typescript';
import {mkdtemp,mkdir,readFile,writeFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,resolve,dirname} from 'node:path';
import {pathToFileURL} from 'node:url';
import {validateMapSnapshot} from '../shared/mapProtocol.mjs';
import {startMapServer} from '../server/mapServer.mjs';
import {exampleSnapshot} from './live-fixture.mjs';
const directory=await mkdtemp(join(tmpdir(),'kafka-cluster-')),checks=[];
let running;
try{
 await mkdir(join(directory,'source'));await writeFile(join(directory,'package.json'),' {"type":"module"}');
 for(const file of ['clusterModel','clusterDemo','scenarioDefault']){const source=await readFile(`src/${file}.ts`,'utf8'),code=ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}}).outputText.replace(/from '(\.\/[^']+)'/g,"from '$1.js'");await writeFile(join(directory,'source',`${file}.js`),code);}
 const {deriveCluster,demoPartitionPlacement,applicationTopology}=await import(pathToFileURL(join(directory,'source/clusterModel.js'))),{defaultScenario}=await import(pathToFileURL(join(directory,'source/scenarioDefault.js')));
 const cluster=deriveCluster(defaultScenario),orders=defaultScenario.topology.topics.find(topic=>topic.id==='orders');assert.deepEqual(cluster.partitions.orders,orders.partitions);assert.equal(cluster.brokers.length,5);assert.equal(cluster.partitions.payments[0].inSyncReplicaBrokerIds.includes('broker-5'),false);checks.push('exact demo orders assignments and an existing replica outside ISR');
 const placements=demoPartitionPlacement(cluster.brokers,10,3);assert.deepEqual(placements,demoPartitionPlacement(cluster.brokers.slice().reverse(),10,3));for(const placement of placements){assert.equal(new Set(placement.replicaBrokerIds).size,3);assert.equal(new Set(placement.replicaBrokerIds.map(id=>cluster.brokers.find(broker=>broker.id===id).zone)).size,3);}assert.throws(()=>demoPartitionPlacement(cluster.brokers,2,6),/exceeds/);checks.push('deterministic rack-aware demo generation and impossible RF rejection');
 const singlePartitionTopics=structuredClone(defaultScenario);singlePartitionTopics.topology.topics=Array.from({length:35},(_,index)=>({id:`events-${index}`,name:`events-${index}`,partitionCount:1,replicationFactor:3}));const distributed=deriveCluster(singlePartitionTopics);assert.equal(new Set(Object.values(distributed.partitions).flat().map(partition=>partition.leaderBrokerId)).size,5);for(const broker of distributed.brokers)assert.ok(Object.values(distributed.partitions).flat().some(partition=>partition.replicaBrokerIds.includes(broker.id)));checks.push('single-partition topics distribute across all five brokers');
 const reported=structuredClone(defaultScenario);reported.cluster.placementMode='reported';delete reported.topology.topics[0].partitions;assert.deepEqual(deriveCluster(reported).partitions.orders,[]);reported.topology.topics[0].partitions=[orders.partitions[2]];assert.deepEqual(deriveCluster(reported).partitions.orders,[orders.partitions[2]]);checks.push('missing/partial reported placement never synthesized');
 const originalKey=JSON.stringify(applicationTopology(defaultScenario.topology));reported.topology.topics[0].partitions[0].leaderBrokerId='broker-5';assert.equal(JSON.stringify(applicationTopology(reported.topology)),originalKey);checks.push('storage state excluded from application geometry key');
 const snapshot=exampleSnapshot();snapshot.cluster.brokers=cluster.brokers;snapshot.topology.topics[0].replicationFactor=3;snapshot.topology.topics[0].partitions=orders.partitions.slice(0,2);assert.deepEqual(validateMapSnapshot(snapshot).topology.topics[0].partitions,snapshot.topology.topics[0].partitions);
 const invalid=change=>{const value=structuredClone(snapshot);change(value);assert.throws(()=>validateMapSnapshot(value));};
 invalid(value=>value.cluster.brokers.push(value.cluster.brokers[0]));invalid(value=>value.topology.topics[0].partitions[0].replicaBrokerIds.push('missing'));invalid(value=>value.topology.topics[0].partitions[0].inSyncReplicaBrokerIds.push('broker-2'));invalid(value=>value.topology.topics[0].partitions[0].leaderBrokerId='broker-2');invalid(value=>value.topology.topics[0].partitions.push(value.topology.topics[0].partitions[0]));invalid(value=>value.topology.topics[0].partitions[0].partitionId=2);invalid(value=>value.cluster.brokers[0].secret='forbidden');invalid(value=>value.cluster.brokers=null);invalid(value=>delete value.cluster.brokers);checks.push('broker, placement, leader, ISR, unknown-field and bounds validation');
 const unknown=structuredClone(snapshot);unknown.topology.topics[0].partitions[0].leaderBrokerId=null;unknown.topology.topics[0].partitions[0].inSyncReplicaBrokerIds=null;assert.deepEqual(validateMapSnapshot(unknown).topology.topics[0].partitions[0],unknown.topology.topics[0].partitions[0]);checks.push('unknown leader/ISR accepted without invented state');
 const token='cluster-protocol-test-token-more-than-32-characters',storageDirectory=join(directory,'data');running=await startMapServer({port:0,token,storageDirectory});const base=`http://127.0.0.1:${running.port}`;
 const response=await fetch(`${base}/api/v1/map`,{method:'PUT',headers:{authorization:`Bearer ${token}`,'content-type':'application/json'},body:JSON.stringify(snapshot)});assert.equal(response.status,200,await response.text());await running.close();running=await startMapServer({port:0,token,storageDirectory});assert.deepEqual((await (await fetch(`http://127.0.0.1:${running.port}/api/v1/map`)).json()).snapshot,snapshot);checks.push('actual authenticated HTTP ingestion and restart preserve replica state');
 const result={checks,mockedData:'Explicit synthetic source observations and built-in demo scenarios only. Actual TypeScript cluster logic, shared validator, HTTP server and persisted files; no Kafka/provider mocks or real cluster.'};await writeFile('discussions/kafka-city/cluster-check.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));
}finally{if(running)await running.close();if(dirname(resolve(directory))!==resolve(tmpdir()))throw new Error('Unexpected temporary directory.');await rm(directory,{recursive:true});}
