import assert from 'node:assert/strict';
export async function runEditorChecks(source){
 const {defaultScenario}=await import(source('scenarioDefault')),{deriveScenario}=await import(source('scenarioDerive')),{validateScenario}=await import(source('scenarioValidation')),{computeLayout}=await import(source('mapLayout')),{computeLayout:placeServices,serviceRole}=await import(source('autoLayout'));
 const actions=await import(source('scenarioActions'));
 const scenario=structuredClone(defaultScenario);scenario.topology={services:[],topics:[],producers:[],consumerGroups:[]};scenario.state={topics:{},consumerGroups:{}};scenario.layout={services:{},terminals:{},topics:{},routes:{},overpasses:[]};scenario.visualization.topicColors={};scenario.visualization.serviceStyles={};
 assert.equal(deriveScenario(scenario).cityRoutes.length,0,'An empty scenario is valid and drawable');
 const orders=actions.addService(scenario,'Orders'),payment=actions.addService(scenario,'Payment'),analytics=actions.addService(scenario,'Analytics'),topic=actions.addTopic(scenario,'orders');scenario.state.topics[topic].messagesPerSecond=10000;
 const producer=actions.connectProducer(scenario,orders,topic,4),receiving=actions.addGroup(scenario,payment,topic,'payment-orders');scenario.topology.consumerGroups.find(group=>group.id===receiving).consumerCount=3;scenario.state.consumerGroups[receiving]={consumptionRate:9500,lag:2000};actions.addGroup(scenario,analytics,topic,'analytics-orders');
 assert.equal(serviceRole(scenario.topology,orders),'source');assert.equal(serviceRole(scenario.topology,payment),'sink');const placed=placeServices(scenario.topology,scenario.layout);assert.ok(placed[orders].u<placed[payment].u);assert.ok(placed[payment].v!==placed[analytics].v,'Related sinks must have separate campus space');
 const map=computeLayout(scenario.topology,scenario.layout),routes=map.routes.filter(route=>route.topic===topic);assert.equal(routes.length,2);assert.deepEqual(routes[0].points.slice(0,3),routes[1].points.slice(0,3),'A topic with multiple groups must share its producer trunk');
 const copiedService=actions.duplicateService(scenario,orders),copiedGroup=actions.duplicateGroup(scenario,receiving),copiedTopic=actions.duplicateTopic(scenario,topic);assert.notEqual(copiedService,orders);assert.notEqual(copiedGroup,receiving);assert.notEqual(copiedTopic,topic);assert.deepEqual(scenario.state.consumerGroups[copiedGroup],scenario.state.consumerGroups[receiving]);assert.equal(scenario.topology.producers.filter(p=>p.serviceId===copiedService).length,2);assert.equal(scenario.state.topics[copiedTopic].messagesPerSecond,10000);validateScenario(scenario);
 const ids=[...scenario.topology.producers,...scenario.topology.consumerGroups].map(item=>item.id);assert.equal(new Set(ids).size,ids.length,'Copied terminal identity keys must remain unique');assert.throws(()=>actions.connectProducer(scenario,orders,topic,1),/already produces/);
 const defaultCopy=structuredClone(defaultScenario),before=computeLayout(defaultCopy.topology,defaultCopy.layout);const building=before.buildings.Payment;actions.moveCampus(defaultCopy,'Payment',building.u+100,building.v+60);const after=computeLayout(defaultCopy.topology,defaultCopy.layout);
 for(const terminal of before.terminals.filter(item=>item.service==='Payment')){const moved=after.terminals.find(item=>item.id===terminal.id);assert.equal(moved.u-terminal.u,100);assert.equal(moved.v-terminal.v,60);}
 assert.deepEqual(after.buildings.Orders,before.buildings.Orders,'Moving one campus preserves unrelated manual placement');assert.ok(!Object.keys(defaultCopy.layout.routes).some(key=>key.startsWith('payment-shipping/')));deriveScenario(defaultCopy);
 const sameNames=structuredClone(defaultScenario);sameNames.topology.services.push({id:'orders',name:'Orders processor'});const labels=deriveScenario(sameNames).labelAnchors;assert.ok(labels['service-orders']&&labels['topic-orders']);assert.notDeepEqual(labels['service-orders'],labels['topic-orders'],'Service/topic labels use separate identities even when IDs match');
 scenario.visualization.labels={serviceSize:16,topicSize:12,poleLength:40,offsetX:0,offsetY:0};scenario.layout.labels={[`service-${orders}`]:{labelAnchor:{x:-20,y:300},labelOffset:{x:30,y:-120}}};const encoded=deriveScenario(scenario).labelAnchors[`service-${orders}`];assert.deepEqual({u:encoded.u,v:encoded.v},{u:-20,v:300});assert.equal(encoded.offsetX,30);assert.equal(encoded.offsetY,-120);const invalid=structuredClone(scenario);invalid.visualization.labels.serviceSize=99;assert.throws(()=>validateScenario(invalid),/Service label size/);
 const {applyScenario,currentScenario}=await import(source('scenarioRuntime')),{clearCampusAnchor,serviceSignAnchor}=await import(source('signAnchors')),{rooftopKeepouts,poleIntersects}=await import(source('buildingFeatures')),{project}=await import(source('isometric'));const original=structuredClone(currentScenario);applyScenario(defaultScenario);const actual=deriveScenario(defaultScenario);
 for(const [id,building] of Object.entries(actual.cityBuildings)){const sign=serviceSignAnchor(id),point=project(sign.u,sign.v),plate={x:point.x+sign.offsetX,y:point.y-sign.rise},anchor=clearCampusAnchor(id,plate),end=project(anchor.u,anchor.v);for(const [other,house] of Object.entries(actual.cityBuildings))for(const keepout of rooftopKeepouts(house,actual.services[other].art))assert.equal(poleIntersects(plate,end,keepout),false,'Default poles must clear actual roof features');}
 const automatic=structuredClone(defaultScenario);automatic.layout={services:{},terminals:{},topics:{},routes:{},overpasses:[]};applyScenario(automatic);const autoModel=deriveScenario(automatic);for(const id of Object.keys(autoModel.cityBuildings)){const sign=serviceSignAnchor(id),point=project(sign.u,sign.v);assert.ok(clearCampusAnchor(id,{x:point.x+sign.offsetX,y:point.y-sign.rise}),'Automatic campuses require clear default poles');}applyScenario(original);
 console.log('PASS: actual editor creation/duplication actions, stable identities, shared automatic trunks, empty scenarios, campus movement, namespaced label overrides and rooftop pole clearance. Mocked data: none.');
}
