import {useEffect,useState} from 'react';
import type {ScenarioConfig} from './scenarioTypes';
import type {Selection} from './model';
import {createPreset,presetNames,type PresetName} from './scenarioPresets';
import {validateScenario} from './scenarioValidation';
import {ServiceSettings} from './ServiceSettings';
import {TopicSettings} from './TopicSettings';
import {GroupSettings} from './GroupSettings';
import {VisualSettings} from './VisualSettings';
import {ScenarioLayoutEditor} from './ScenarioLayoutEditor';
import {AdvancedJson} from './AdvancedJson';
import {Field} from './ScenarioFields';
import {addTopic,addGroup,newId} from './scenarioActions';
const sections=['SERVICES','TOPICS','CONSUMER GROUPS','LAYOUT','VISUALS','SCENARIOS','ADVANCED JSON'];
export function CityEditor({open,configuration,selected,onApply,onClose,onLayoutMode,layoutMode}:{open:boolean;configuration:ScenarioConfig;selected:Selection|null;onApply:(config:ScenarioConfig)=>void;onClose:()=>void;onLayoutMode:(enabled:boolean)=>void;layoutMode:boolean}){
 const [draft,setDraft]=useState(()=>structuredClone(configuration)),[baseline,setBaseline]=useState(()=>createPreset('Demo')),[preset,setPreset]=useState<PresetName>('Demo'),[section,setSection]=useState('SERVICES'),[objectId,setObjectId]=useState(''),[contextService,setContextService]=useState<string|undefined>(),[contextTopic,setContextTopic]=useState<string|undefined>(),[error,setError]=useState(''),[message,setMessage]=useState('');
 useEffect(()=>{if(open){setDraft(structuredClone(configuration));setError('');setMessage('');}},[open]);
 useEffect(()=>{if(!open||!selected)return;if(selected.kind==='service'){setSection('SERVICES');setObjectId(selected.name);}else if(selected.kind==='topic'){setSection('TOPICS');setObjectId(selected.name);}else if(selected.kind==='terminal'){setSection(selected.producer?'SERVICES':'CONSUMER GROUPS');setObjectId(selected.producer?selected.name:selected.id);}},[selected,open]);
 useEffect(()=>{if(open)setDraft(previous=>({...previous,layout:structuredClone(configuration.layout)}));},[configuration]);
 useEffect(()=>{if(!open||section!=='LAYOUT')onLayoutMode(false);},[open,section]);
 if(!open)return null;
 const edit=(change:(config:ScenarioConfig)=>void)=>{try{const copy=structuredClone(draft);change(copy);setDraft(copy);setError('');setMessage('Draft changed. Apply structural edits to update the city.');}catch(reason){setError(String(reason));}};
 const apply=(value:unknown)=>{try{const valid=validateScenario(value);onApply(valid);setDraft(valid);setError('');setMessage(`${valid.metadata.name} applied: ${valid.topology.services.length} services, ${valid.topology.topics.length} topics.`);return true;}catch(reason){setError(String(reason));setMessage('Scenario was not applied. The current city remains active.');console.error(reason);return false;}};
 const loadPreset=()=>{try{const next=createPreset(preset);setDraft(next);if(apply(next)){setBaseline(structuredClone(next));setObjectId('');setContextService(undefined);setContextTopic(undefined);}}catch(reason){setError(String(reason));setMessage('Preset could not be loaded.');console.error(reason);}};
 const exportJson=()=>{try{const valid=validateScenario(draft),url=URL.createObjectURL(new Blob([JSON.stringify(valid,null,2)],{type:'application/json'})),link=document.createElement('a');link.href=url;link.download=`${valid.metadata.id}.json`;link.click();URL.revokeObjectURL(url);setMessage('Scenario exported');setError('');}catch(reason){setError(String(reason));}};
 const newGroup=(service?:string,topic?:string)=>{setContextService(service);setContextTopic(topic);edit(copy=>{setObjectId(addGroup(copy,service??copy.topology.services[0].id,topic??copy.topology.topics[0].id));});setSection('CONSUMER GROUPS');};
 return <aside className="scenario-drawer guided-drawer" role="dialog" aria-modal="false" aria-label="Scenario configuration"><div className="scenario-heading"><h2>Edit Kafka City</h2><button aria-label="Close configuration" onClick={onClose}>×</button></div><div className="editor-shell"><nav aria-label="Configuration sections">{sections.map(name=><button key={name} className={section===name?'chosen':''} aria-current={section===name?'page':undefined} onClick={()=>setSection(name)}>{name}</button>)}</nav><div className="scenario-content">
 {section==='SERVICES'&&<ServiceSettings config={draft} edit={edit} selectedId={objectId} onGroup={service=>newGroup(service)} onTopic={service=>{setContextService(service);edit(copy=>{setObjectId(addTopic(copy));});setSection('TOPICS');}}/>}
 {section==='TOPICS'&&<TopicSettings config={draft} edit={edit} selectedId={objectId} producerService={contextService} onGroup={topic=>newGroup(undefined,topic)}/>}
 {section==='CONSUMER GROUPS'&&<GroupSettings config={draft} edit={edit} selectedId={objectId} serviceId={contextService} topicId={contextTopic}/>}
 {section==='VISUALS'&&<VisualSettings config={draft} edit={edit}/>}
 {section==='LAYOUT'&&<div><h3>Layout</h3><p>Drag a service to move its campus, including terminals. Roads reroute after drop. Apply new services first so they appear on the map.</p><button aria-pressed={layoutMode} onClick={()=>onLayoutMode(!layoutMode)}>{layoutMode?'Stop moving campuses':'Move campuses on map'}</button><button onClick={()=>edit(copy=>{copy.layout={services:{},terminals:{},topics:{},routes:{},overpasses:[]};})}>Reset to auto layout</button><p className="scenario-help">Auto layout groups connected services into districts and reserves campus space for buildings, bays, driveways and road widths. Manual service coordinates remain fixed.</p><details><summary>Advanced coordinates, terminals and roads</summary><ScenarioLayoutEditor config={draft} edit={edit}/></details></div>}
 {section==='SCENARIOS'&&<div><h3>Scenarios</h3><Field label="Scenario name" type="text" value={draft.metadata.name} onChange={value=>edit(copy=>{copy.metadata.name=value;})}/><label className="scenario-field">Preset<select aria-label="Scenario preset" value={preset} onChange={event=>setPreset(event.target.value as PresetName)}>{presetNames.map(name=><option key={name}>{name}</option>)}</select></label><button onClick={loadPreset}>Load preset</button><p className="scenario-help" role="status">Current city: {configuration.metadata.name} · {configuration.topology.services.length} services · {configuration.topology.topics.length} topics. Load preset updates the city immediately.</p><button onClick={()=>edit(copy=>{copy.metadata={id:newId('scenario',[copy.metadata.id]),name:copy.metadata.name+' copy'};})}>Duplicate scenario</button><button onClick={()=>apply(structuredClone(baseline))}>Reset preset</button><button onClick={()=>{const next=createPreset('Normal');next.metadata={id:'new-scenario',name:'New scenario'};next.topology={services:[],topics:[],producers:[],consumerGroups:[]};next.state={topics:{},consumerGroups:{}};next.layout={services:{},terminals:{},topics:{},routes:{},overpasses:[]};next.visualization.topicColors={};next.visualization.serviceStyles={};setDraft(next);setObjectId('');setSection('SERVICES');setMessage('Add a service to begin.');}}>New empty scenario</button><button onClick={exportJson}>Export JSON</button><label className="import-button">Import JSON<input aria-label="Import JSON" type="file" accept=".json,application/json" onChange={async event=>{const file=event.target.files?.[0];if(!file)return;try{if(file.size>1000000)throw new Error('Configuration JSON must be smaller than 1 MB');const imported=validateScenario(JSON.parse(await file.text()));setDraft(imported);setBaseline(structuredClone(imported));setObjectId('');setError('');setMessage('JSON imported. Apply to update the city.');}catch(reason){setError(String(reason));}event.target.value='';}}/></label></div>}
 {section==='ADVANCED JSON'&&<AdvancedJson config={draft} onApply={apply}/>}
 </div></div>{error&&<div className="scenario-error" role="alert">{error}</div>}{message&&<p className="scenario-message" role="status">{message}</p>}<footer className="scenario-actions"><button onClick={()=>apply(draft)}>Apply</button><button onClick={exportJson}>Export JSON</button><button onClick={onClose}>Done</button></footer></aside>;
}
