import {useState} from 'react';
import {Field,Choice,nextId,type EditorProps} from './ScenarioFields';
import {deriveCluster,demoPartitionPlacement,placementStart} from './clusterModel';
import type {PartitionPlacement,ClusterModel} from './scenarioTypes';
export function ClusterSettings({config,edit}:EditorProps){
 const [topicId,setTopicId]=useState(config.topology.topics[0]?.id??''),brokers=config.cluster?.brokers??[],topic=config.topology.topics.find(topic=>topic.id===topicId);
 let derived:ClusterModel|undefined,previewError='';try{derived=deriveCluster(config);}catch(reason){previewError=String(reason);}
 const changePartition=(partitionId:number,change:(partition:PartitionPlacement)=>void)=>edit(draft=>{
  const item=draft.topology.topics.find(topic=>topic.id===topicId)!;
  if(!derived)throw new Error(previewError);
  if(item.partitions===undefined)item.partitions=structuredClone(derived.partitions[topicId]);
  let partition=item.partitions.find(partition=>partition.partitionId===partitionId);
  if(!partition){partition={partitionId,leaderBrokerId:null,replicaBrokerIds:[],inSyncReplicaBrokerIds:null};item.partitions.push(partition);}
  change(partition);
 });
 return <div><h3>Cluster</h3><p className="scenario-help">Demo placement controls. Explicit placements are preserved. Missing live placement is never generated.</p>
 {previewError&&<p className="scenario-error" role="alert">Placement preview failed: {previewError}</p>}
 {brokers.map(broker=><section key={broker.id}><h4>{broker.id}</h4><Field label={`${broker.id} name`} type="text" value={broker.name} onChange={value=>edit(draft=>{draft.cluster!.brokers.find(item=>item.id===broker.id)!.name=value;})}/>{(['rack','zone'] as const).map(key=><Field key={key} label={`${broker.id} ${key==='zone'?'availability zone':'rack'}`} type="text" value={broker[key]??''} onChange={value=>edit(draft=>{const item=draft.cluster!.brokers.find(item=>item.id===broker.id)!;if(value)item[key]=value;else delete item[key];})}/>)}<button onClick={()=>edit(draft=>{if(Object.values(deriveCluster(draft).partitions).flat().some(partition=>partition.replicaBrokerIds.includes(broker.id)))throw new Error(`Remove ${broker.name} from its partition replica sets before deleting it.`);draft.cluster!.brokers=draft.cluster!.brokers.filter(item=>item.id!==broker.id);})}>Remove broker</button></section>)}
 <button onClick={()=>edit(draft=>{draft.cluster??={brokers:[],placementMode:'demo'};if(draft.cluster.brokers.length>=64)throw new Error('The map supports at most 64 brokers.');const id=nextId('broker',draft.cluster.brokers.map(broker=>broker.id));draft.cluster.brokers.push({id,name:`Broker ${id.split('-').at(-1)}`});})}>Add broker</button>
 {config.topology.topics.length>0&&<><h3>Partition placement</h3><Choice label="Placement topic" value={topic?.id??''} options={[{id:'',name:'Choose topic'},...config.topology.topics]} onChange={setTopicId}/>{topic&&<><Field label="Replication factor" value={topic.replicationFactor??1} onChange={value=>edit(draft=>{draft.topology.topics.find(item=>item.id===topic.id)!.replicationFactor=Number(value);})}/><button onClick={()=>edit(draft=>{const item=draft.topology.topics.find(item=>item.id===topic.id)!;if(!draft.cluster?.brokers.length)throw new Error('Add brokers before generating demo placement.');item.partitions=demoPartitionPlacement(draft.cluster.brokers,item.partitionCount,item.replicationFactor??1,placementStart(item.id));})}>Generate demo placement for this topic</button>
 {Array.from({length:topic.partitionCount},(_,partitionId)=>{
  const partition=derived?.partitions[topicId]?.find(partition=>partition.partitionId===partitionId);
  return <details key={`${topicId}/${partitionId}`} className="partition-editor"><summary>P{partitionId} · {partition?`${partition.replicaBrokerIds.length} replicas · ${partition.leaderBrokerId??'leader unknown'}`:'Placement unknown'}</summary><Choice label={`P${partitionId} leader`} value={partition?.leaderBrokerId??''} options={[{id:'',name:'Unknown / no elected leader'},...brokers.filter(broker=>partition?.replicaBrokerIds.includes(broker.id))]} onChange={value=>changePartition(partitionId,partition=>{partition.leaderBrokerId=value||null;})}/><fieldset><legend>Replica brokers</legend>{brokers.map(broker=><label key={broker.id}><input aria-label={`P${partitionId} replica ${broker.id}`} type="checkbox" checked={partition?.replicaBrokerIds.includes(broker.id)??false} onChange={event=>changePartition(partitionId,partition=>{if(event.target.checked)partition.replicaBrokerIds.push(broker.id);else{partition.replicaBrokerIds=partition.replicaBrokerIds.filter(id=>id!==broker.id);if(partition.leaderBrokerId===broker.id)partition.leaderBrokerId=null;if(partition.inSyncReplicaBrokerIds)partition.inSyncReplicaBrokerIds=partition.inSyncReplicaBrokerIds.filter(id=>id!==broker.id);}})}/>{broker.name}</label>)}</fieldset><label><input type="checkbox" aria-label={`P${partitionId} ISR unknown`} checked={!partition||partition.inSyncReplicaBrokerIds===null} onChange={event=>changePartition(partitionId,partition=>{partition.inSyncReplicaBrokerIds=event.target.checked?null:[];})}/> ISR not supplied</label>{partition?.inSyncReplicaBrokerIds!==null&&partition&&<fieldset><legend>In-sync replicas</legend>{brokers.filter(broker=>partition.replicaBrokerIds.includes(broker.id)).map(broker=><label key={broker.id}><input type="checkbox" aria-label={`P${partitionId} ISR ${broker.id}`} checked={partition.inSyncReplicaBrokerIds!.includes(broker.id)} onChange={event=>changePartition(partitionId,partition=>{if(event.target.checked)partition.inSyncReplicaBrokerIds!.push(broker.id);else partition.inSyncReplicaBrokerIds=partition.inSyncReplicaBrokerIds!.filter(id=>id!==broker.id);})}/>{broker.name}</label>)}</fieldset>}</details>;
 })}</>}</>}
 </div>;
}
