import {useEffect,useState} from 'react';
import {Field,Choice,cleanReferences,type EditorProps} from './ScenarioFields';
import {addGroup,duplicateGroup} from './scenarioActions';
import {LabelSettings} from './LabelSettings';
export function GroupSettings({config,edit,focused=false,selectedId,serviceId,topicId}:{focused?:boolean;selectedId:string;serviceId?:string;topicId?:string}&EditorProps){const [id,setId]=useState(selectedId),[search,setSearch]=useState('');useEffect(()=>{setId(selectedId);},[selectedId]);const group=config.topology.consumerGroups.find(item=>item.id===id),snapshot=group?config.state.consumerGroups[group.id]:undefined;
 return <div><h3>Consumer groups</h3>{!focused&&<><input aria-label="Search consumer groups" placeholder="Search groups" value={search} onChange={event=>setSearch(event.target.value)}/>{!config.topology.consumerGroups.length&&<p>No consumer groups yet. Choose a service and subscribe it to a topic.</p>}<div className="object-list">{config.topology.consumerGroups.filter(item=>item.name.toLowerCase().includes(search.toLowerCase())).map(item=><button key={item.id} className={id===item.id?'chosen':''} onClick={()=>setId(item.id)}><strong>{item.name}</strong><small>{config.topology.services.find(service=>service.id===item.serviceId)!.name} · {item.consumerCount} consumers · lag {config.state.consumerGroups[item.id].lag.toLocaleString()}</small></button>)}</div><button disabled={!config.topology.services.length||!config.topology.topics.length} onClick={()=>edit(draft=>{setId(addGroup(draft,serviceId??draft.topology.services[0].id,topicId??draft.topology.topics[0].id));})}>Add consumer group</button>
 </>}{group&&snapshot&&<section><Choice label="Receiving service" value={group.serviceId} options={config.topology.services} onChange={value=>edit(draft=>{draft.topology.consumerGroups.find(item=>item.id===id)!.serviceId=value;delete draft.layout.terminals[id];})}/><Field label="Consumer group name" type="text" value={group.name} onChange={value=>edit(draft=>{draft.topology.consumerGroups.find(item=>item.id===id)!.name=value;})}/><fieldset><legend>Subscribed topics</legend>{config.topology.topics.map(topic=><label className="scenario-check" key={topic.id}><input type="checkbox" checked={group.topicIds.includes(topic.id)} onChange={event=>edit(draft=>{const item=draft.topology.consumerGroups.find(item=>item.id===id)!;item.topicIds=event.target.checked?[...item.topicIds,topic.id]:item.topicIds.filter(value=>value!==topic.id);for(const key of Object.keys(draft.layout.routes))if(key.endsWith('/'+id))delete draft.layout.routes[key];})}/>{topic.name}</label>)}</fieldset><Field label="Consumer count" value={group.consumerCount} onChange={value=>edit(draft=>{draft.topology.consumerGroups.find(item=>item.id===id)!.consumerCount=Number(value);})}/><Field label="Consumption messages/sec" value={snapshot.consumptionRate} onChange={value=>edit(draft=>{draft.state.consumerGroups[id].consumptionRate=Number(value);})}/><Field label="Current lag" value={snapshot.lag} onChange={value=>edit(draft=>{draft.state.consumerGroups[id].lag=Number(value);})}/><button onClick={()=>edit(draft=>{setId(duplicateGroup(draft,id));})}>Duplicate consumer group</button><button onClick={()=>edit(draft=>{draft.topology.consumerGroups=draft.topology.consumerGroups.filter(item=>item.id!==id);cleanReferences(draft);setId('');})}>Delete consumer group</button><details><summary>Advanced receiving-yard settings</summary><Choice label="Campus side" value={config.layout.terminals[id]?.side??'south'} options={[{id:'east',name:'North-east'},{id:'south',name:'South-east'},{id:'west',name:'South-west'},{id:'north',name:'North-west'}]} onChange={value=>edit(draft=>{draft.layout.terminals[id]={side:value as 'south',offset:.5,wall:value==='east'||value==='west'?'side':'front'};})}/><Field label="Position along campus side" type="range" step="0.05" value={config.layout.terminals[id]?.offset??.5} onChange={value=>edit(draft=>{draft.layout.terminals[id]={...draft.layout.terminals[id],offset:Number(value)};})}/><LabelSettings id={id} config={config} edit={edit}/></details></section>}
 </div>;
}
