import type {ScenarioConfig} from './scenarioTypes';
function fail(path:string,message:string):never{throw new Error(`${path}: ${message}`);}
function object(value:unknown,path:string):Record<string,any>{if(!value||typeof value!=='object'||Array.isArray(value))fail(path,'expected an object');return value as Record<string,any>;}
function list(value:unknown,path:string,min=0,max=64):any[]{if(!Array.isArray(value)||value.length<min||value.length>max)fail(path,`expected ${min}–${max} entries`);return value;}
function number(value:unknown,path:string,min=0,max=1e12,integer=false){if(typeof value!=='number'||!Number.isFinite(value)||value<min||value>max||(integer&&!Number.isInteger(value)))fail(path,`expected ${integer?'an integer':'a number'} from ${min} to ${max}`);}
function text(value:unknown,path:string,id=false){if(typeof value!=='string'||!value.trim()||value.length>80||(id&&!/^[A-Za-z][\w.-]*$/.test(value)))fail(path,id?'use an ID starting with a letter, with letters, digits, . _ or -':'expected nonempty text up to 80 characters');}
function color(value:unknown,path:string){if(typeof value!=='string'||!/^#[0-9a-f]{6}$/i.test(value))fail(path,'expected a six-digit hex color');}
function point(value:unknown,path:string,partial=false){const p=object(value,path);for(const axis of ['u','v'])if(!partial||p[axis]!==undefined)number(p[axis],`${path}.${axis}`,-10000,10000);for(const size of ['width','depth'])if(p[size]!==undefined)number(p[size],`${path}.${size}`,20,2000);}
function unique(entries:any[],path:string){const ids=new Set<string>();entries.forEach((entry,index)=>{object(entry,`${path}[${index}]`);text(entry.id,`${path}[${index}].id`,true);if(ids.has(entry.id))fail(path,`duplicate ID ${entry.id}`);ids.add(entry.id);});return ids;}
function reference(id:unknown,ids:Set<string>,path:string){if(typeof id!=='string'||!ids.has(id))fail(path,`unknown reference ${String(id)}`);}
export function validateScenario(value:unknown):ScenarioConfig {
 const config=object(value,'configuration');if(config.version!==1)fail('version','only schema version 1 is supported');
 const metadata=object(config.metadata,'metadata');text(metadata.id,'metadata.id',true);text(metadata.name,'metadata.name');
 const topology=object(config.topology,'topology');
 const services=list(topology.services,'topology.services',0,16),topics=list(topology.topics,'topology.topics',0,16),producers=list(topology.producers,'topology.producers',0,64),groups=list(topology.consumerGroups,'topology.consumerGroups',0,64);
 const serviceIds=unique(services,'services'),topicIds=unique(topics,'topics'),producerIds=unique(producers,'producers'),groupIds=unique(groups,'consumerGroups');
 for(const groupId of groupIds)if(producerIds.has(groupId))fail('terminals',`producer/group IDs must be distinct: ${groupId}`);
 services.forEach(service=>text(service.name,`service ${service.id}.name`));
 topics.forEach(topic=>{text(topic.name,`topic ${topic.id}.name`);number(topic.partitionCount,`topic ${topic.id}.partitionCount`,1,32,true);});
 const producerPairs=new Set<string>();
 producers.forEach(producer=>{reference(producer.serviceId,serviceIds,`producer ${producer.id}.serviceId`);reference(producer.topicId,topicIds,`producer ${producer.id}.topicId`);number(producer.producerCount,`producer ${producer.id}.producerCount`,1,32,true);const key=`${producer.serviceId}/${producer.topicId}`;if(producerPairs.has(key))fail('producers',`combine duplicate service/topic producer counts: ${key}`);producerPairs.add(key);});
 groups.forEach(group=>{text(group.name,`group ${group.id}.name`);reference(group.serviceId,serviceIds,`group ${group.id}.serviceId`);const subscriptions=list(group.topicIds,`group ${group.id}.topicIds`,1,16);if(new Set(subscriptions).size!==subscriptions.length)fail(`group ${group.id}.topicIds`,'duplicate subscription');subscriptions.forEach(id=>reference(id,topicIds,`group ${group.id}.topicIds`));number(group.consumerCount,`group ${group.id}.consumerCount`,1,32,true);});
 const state=object(config.state,'state'),topicState=object(state.topics,'state.topics'),groupState=object(state.consumerGroups,'state.consumerGroups');
 for(const id of Object.keys(topicState))reference(id,topicIds,'state.topics');for(const id of Object.keys(groupState))reference(id,groupIds,'state.consumerGroups');
 topics.forEach(topic=>{const snapshot=object(topicState[topic.id],`state.topics.${topic.id}`);number(snapshot.messagesPerSecond,`${topic.id}.messagesPerSecond`);const overrides=snapshot.partitionOverrides===undefined?{}:object(snapshot.partitionOverrides,`${topic.id}.partitionOverrides`);let sum=0;for(const [key,rate] of Object.entries(overrides)){if(!/^\d+$/.test(key)||Number(key)>=topic.partitionCount)fail(`${topic.id}.partitionOverrides`,`${key} is not a valid partition`);number(rate,`${topic.id}.P${key}`);sum+=rate as number;}if(sum>snapshot.messagesPerSecond)fail(`${topic.id}.partitionOverrides`,'explicit rates exceed the topic total');if(Object.keys(overrides).length===topic.partitionCount&&Math.abs(sum-snapshot.messagesPerSecond)>.000001)fail(`${topic.id}.partitionOverrides`,'when every partition is overridden, rates must sum to the topic total');});
 groups.forEach(group=>{const snapshot=object(groupState[group.id],`state.consumerGroups.${group.id}`);number(snapshot.consumptionRate,`${group.id}.consumptionRate`);number(snapshot.lag,`${group.id}.lag`);});
 const visual=object(config.visualization,'visualization'),vehicles=object(visual.vehicles,'visualization.vehicles');
 for(const kind of ['car','van','truck','semi'])number(object(vehicles[kind],`vehicles.${kind}`).messagesPerVehicle,`${kind}.messagesPerVehicle`,1);
 number(object(vehicles.trailer,'vehicles.trailer').messagesPerTrailer,'trailer.messagesPerTrailer',1);
 const thresholds=object(visual.thresholds,'visualization.thresholds');let previous=-1;for(const kind of ['car','van','truck','semi']){number(thresholds[kind],`thresholds.${kind}`);if(thresholds[kind]<=previous)fail('thresholds','must strictly increase from car to van to truck to semi');previous=thresholds[kind];}
 for(const [field,min,max] of [['maxTrailers',1,8],['maxVehiclesPerLane',1,50],['maxVehiclesPerTopic',1,500],['maxQueueVehicles',0,100],['maxVehiclesTotal',1,500]] as const)number(visual[field],`visualization.${field}`,min,max,true);
 number(visual.messagesPerQueueVehicle,'messagesPerQueueVehicle',1);number(visual.trafficWindowSeconds,'trafficWindowSeconds',.1,60);
 for(const [id,hex] of Object.entries(object(visual.topicColors,'topicColors'))){reference(id,topicIds,'topicColors');color(hex,`topicColors.${id}`);}
 for(const [id,styleValue] of Object.entries(object(visual.serviceStyles,'serviceStyles'))){reference(id,serviceIds,'serviceStyles');const style=object(styleValue,`serviceStyles.${id}`);color(style.color,`${id}.color`);if(style.palette!==undefined)list(style.palette,`${id}.palette`,3,3).forEach(hex=>color(hex,`${id}.palette`));if(style.art!==undefined&&!['Orders','Payment','Analytics','Notification','Office'].includes(style.art))fail(`${id}.art`,'unknown building artwork');}
 const layout=object(config.layout,'layout'),placements=object(layout.services,'layout.services');for(const [id,p] of Object.entries(placements)){reference(id,serviceIds,'layout.services');point(p,`layout.services.${id}`);}
 if(visual.labels!==undefined){const labels=object(visual.labels,'visualization.labels');number(labels.serviceSize,'Service label size',14,18);number(labels.topicSize,'Topic label size',10,16);number(labels.poleLength,'Pole length',20,400);number(labels.offsetX,'Label horizontal offset',-400,400);number(labels.offsetY,'Label vertical offset',-400,400);}
 if(layout.labels!==undefined)for(const [id,value] of Object.entries(object(layout.labels,'layout.labels'))){if(!serviceIds.has(id)&&!topicIds.has(id)&&!producerIds.has(id)&&!groupIds.has(id)&&!(id.startsWith('service-')&&serviceIds.has(id.slice(8)))&&!(id.startsWith('topic-')&&topicIds.has(id.slice(6)))&&!(id.startsWith('terminal-')&&(producerIds.has(id.slice(9))||groupIds.has(id.slice(9)))))fail('layout.labels',`Unknown label object ${id}`);const placement=object(value,`label ${id}`);for(const field of ['labelAnchor','labelOffset']){const pair=object(placement[field],`${id}.${field}`);number(pair.x,`${id}.${field}.x`,-10000,10000);number(pair.y,`${id}.${field}.y`,-10000,10000);}}
 for(const [id,p] of Object.entries(object(layout.terminals,'layout.terminals'))){if(!producerIds.has(id)&&!groupIds.has(id))fail('layout.terminals',`unknown terminal ${id}`);point(p,`layout.terminals.${id}`,true);const placement=object(p,id);if(placement.wall!==undefined&&!['front','side'].includes(placement.wall))fail(id,'wall must be front or side');if(placement.side!==undefined&&!['north','south','east','west'].includes(placement.side))fail(id,'side must be north, south, east or west');if(placement.offset!==undefined)number(placement.offset,`${id}.offset`,0,1);}
 const waypoints=(points:unknown,path:string)=>list(points,path,2,80).forEach((p,index)=>point(p,`${path}[${index}]`));
 for(const [id,topicLayout] of Object.entries(object(layout.topics,'layout.topics'))){reference(id,topicIds,'layout.topics');const placement=object(topicLayout,id);if(placement.waypoints!==undefined)waypoints(placement.waypoints,`${id}.waypoints`);if(placement.branches!==undefined)for(const [groupId,points] of Object.entries(object(placement.branches,`${id}.branches`))){reference(groupId,groupIds,`${id}.branches`);waypoints(points,`${id}.branches.${groupId}`);}}
 for(const [key,routeValue] of Object.entries(object(layout.routes,'layout.routes'))){const [producerId,groupId,...extra]=key.split('/');if(extra.length)fail('layout.routes',`invalid route key ${key}`);reference(producerId,producerIds,'layout.routes');reference(groupId,groupIds,'layout.routes');const producer=producers.find(p=>p.id===producerId),group=groups.find(g=>g.id===groupId);if(!group.topicIds.includes(producer.topicId))fail('layout.routes',`${key} is not a Kafka connection`);const route=object(routeValue,key);waypoints(route.waypoints,key);if(route.branch!==undefined&&typeof route.branch!=='boolean')fail(key,'branch must be boolean');}
 const bridges=list(layout.overpasses,'layout.overpasses',0,32);unique(bridges,'overpasses');bridges.forEach(bridge=>{point(bridge,bridge.id);reference(bridge.topic,topicIds,`${bridge.id}.topic`);number(bridge.height,`${bridge.id}.height`,8,150);number(bridge.start,`${bridge.id}.start`,-10000,10000);number(bridge.ramp,`${bridge.id}.ramp`,20,300);number(bridge.deck,`${bridge.id}.deck`,20,6000);if(Math.abs(bridge.v-(bridge.start+bridge.ramp+bridge.deck/2))>.01)fail(bridge.id,'v must be the center of the straight bridge deck');});
 if(layout.terrainOutline!==undefined)list(layout.terrainOutline,'terrainOutline',3,80).forEach((p,index)=>{list(p,`terrainOutline[${index}]`,2,2).forEach(n=>number(n,'terrain coordinate',-10000,10000));});
 if(layout.worldBounds!==undefined){const bounds=object(layout.worldBounds,'worldBounds');number(bounds.x,'worldBounds.x',-20000,20000);number(bounds.y,'worldBounds.y',-20000,20000);number(bounds.width,'worldBounds.width',100,8000);number(bounds.height,'worldBounds.height',100,8000);}
 return structuredClone(value) as ScenarioConfig;
}
