import {automaticColor} from './scenarioEncoding';
import {Field,Choice,nextId,cleanReferences,type EditorProps} from './ScenarioFields';
export function ScenarioTopologyEditor({config,edit}:EditorProps){const topology=config.topology;
 return <div>
 <h3>Services</h3><p className="scenario-help">Removing a service also removes its Kafka participation and layout overrides.</p>
 {topology.services.map(service=><section key={service.id}><small>{service.id}</small><Field label={`${service.id} service name`} type="text" value={service.name} onChange={value=>edit(draft=>{draft.topology.services.find(item=>item.id===service.id)!.name=value;})}/><button onClick={()=>edit(draft=>{draft.topology.services=draft.topology.services.filter(item=>item.id!==service.id);cleanReferences(draft);})}>Remove service</button></section>)}
 <button onClick={()=>edit(draft=>{const id=nextId('service',draft.topology.services.map(service=>service.id));draft.topology.services.push({id,name:'New service'});})}>Add service</button>
 <h3>Topics</h3>{topology.topics.map(topic=><section key={topic.id}><small>{topic.id}</small><Field label={`${topic.id} topic name`} type="text" value={topic.name} onChange={value=>edit(draft=>{draft.topology.topics.find(item=>item.id===topic.id)!.name=value;})}/><Field label={`${topic.id} partitions`} value={topic.partitionCount} onChange={value=>edit(draft=>{draft.topology.topics.find(item=>item.id===topic.id)!.partitionCount=Number(value);})}/><Field label={`${topic.id} color`} type="color" value={config.visualization.topicColors[topic.id]??automaticColor(topic.id)} onChange={value=>edit(draft=>{draft.visualization.topicColors[topic.id]=value;})}/><button onClick={()=>edit(draft=>{draft.topology.topics=draft.topology.topics.filter(item=>item.id!==topic.id);cleanReferences(draft);})}>Remove topic</button></section>)}
 <button onClick={()=>edit(draft=>{const id=nextId('topic',draft.topology.topics.map(topic=>topic.id));draft.topology.topics.push({id,name:'New topic',partitionCount:2});draft.state.topics[id]={messagesPerSecond:1000};draft.visualization.topicColors[id]='#66a887';})}>Add topic</button>
 <h3>Producers</h3><p className="scenario-help">Count controls bays, not messages per second.</p>
 {topology.producers.map(producer=><section key={producer.id}><small>{producer.id}</small><Choice label={`${producer.id} service`} value={producer.serviceId} options={topology.services} onChange={value=>edit(draft=>{draft.topology.producers.find(item=>item.id===producer.id)!.serviceId=value;delete draft.layout.terminals[producer.id];})}/><Choice label={`${producer.id} topic`} value={producer.topicId} options={topology.topics} onChange={value=>edit(draft=>{draft.topology.producers.find(item=>item.id===producer.id)!.topicId=value;for(const key of Object.keys(draft.layout.routes))if(key.startsWith(producer.id+'/'))delete draft.layout.routes[key];})}/><Field label={`${producer.id} producer count`} value={producer.producerCount} onChange={value=>edit(draft=>{draft.topology.producers.find(item=>item.id===producer.id)!.producerCount=Number(value);})}/><button onClick={()=>edit(draft=>{draft.topology.producers=draft.topology.producers.filter(item=>item.id!==producer.id);cleanReferences(draft);})}>Remove producer connection</button></section>)}
 <button disabled={!topology.topics.length||!topology.services.length} onClick={()=>edit(draft=>{const pair=draft.topology.services.flatMap(service=>draft.topology.topics.map(topic=>({service,topic}))).find(({service,topic})=>!draft.topology.producers.some(producer=>producer.serviceId===service.id&&producer.topicId===topic.id));if(!pair)throw new Error('Every service/topic pair already has a producer connection. Edit counts or add a service/topic.');const {service,topic}=pair;const id=nextId('producer',draft.topology.producers.map(producer=>producer.id));draft.topology.producers.push({id,serviceId:service.id,topicId:topic.id,producerCount:1});})}>Add producer connection</button>
 <h3>Consumer groups</h3>{topology.consumerGroups.map(group=><section key={group.id}><small>{group.id}</small><Field label={`${group.id} group name`} type="text" value={group.name} onChange={value=>edit(draft=>{draft.topology.consumerGroups.find(item=>item.id===group.id)!.name=value;})}/><Choice label={`${group.id} service`} value={group.serviceId} options={topology.services} onChange={value=>edit(draft=>{draft.topology.consumerGroups.find(item=>item.id===group.id)!.serviceId=value;delete draft.layout.terminals[group.id];})}/><fieldset><legend>Subscribed topics</legend>{topology.topics.map(topic=><label className="scenario-check" key={topic.id}><input type="checkbox" checked={group.topicIds.includes(topic.id)} onChange={event=>edit(draft=>{const item=draft.topology.consumerGroups.find(item=>item.id===group.id)!;item.topicIds=event.target.checked?[...item.topicIds,topic.id]:item.topicIds.filter(id=>id!==topic.id);for(const key of Object.keys(draft.layout.routes))if(key.endsWith('/'+group.id))delete draft.layout.routes[key];})}/>{topic.name}</label>)}</fieldset><Field label={`${group.id} consumer count`} value={group.consumerCount} onChange={value=>edit(draft=>{draft.topology.consumerGroups.find(item=>item.id===group.id)!.consumerCount=Number(value);})}/><button onClick={()=>edit(draft=>{draft.topology.consumerGroups=draft.topology.consumerGroups.filter(item=>item.id!==group.id);cleanReferences(draft);})}>Remove group</button></section>)}
 <button disabled={!topology.topics.length||!topology.services.length} onClick={()=>edit(draft=>{const id=nextId('group',draft.topology.consumerGroups.map(group=>group.id));draft.topology.consumerGroups.push({id,name:'New group',serviceId:draft.topology.services[0].id,topicIds:[draft.topology.topics[0].id],consumerCount:2});draft.state.consumerGroups[id]={consumptionRate:1000,lag:0};})}>Add consumer group</button>
 </div>;
}
