import {moveCampus} from './scenarioActions';
import {useEffect,useState} from 'react';
import {Field,Choice,type EditorProps} from './ScenarioFields';
import {buildLayout} from './scenarioLayout';
import type {Point} from './scenarioTypes';
function Waypoints({label,value,onChange}:{label:string;value:Point[]|undefined;onChange:(points:Point[]|undefined)=>void}){
 const [text,setText]=useState(JSON.stringify(value??[],null,2)),[error,setError]=useState('');useEffect(()=>{setText(JSON.stringify(value??[],null,2));setError('');},[JSON.stringify(value)]);
 return <div className="waypoint-editor"><label>{label}<textarea aria-label={label} value={text} onChange={event=>setText(event.target.value)}/></label><button onClick={()=>{try{const points:unknown=JSON.parse(text);if(!Array.isArray(points)||points.some(point=>!point||typeof point.u!=='number'||typeof point.v!=='number'||!Number.isFinite(point.u)||!Number.isFinite(point.v)))throw new Error('Use an array of world-coordinate objects: [{"u": 200, "v": 400}, ...]');if(points.length===1)throw new Error('Use at least two waypoints, or [] for automatic routing.');onChange(points.length?points:undefined);setError('');}catch(reason){setError(String(reason));}}}>Use waypoints</button>{error&&<p role="alert">{error}</p>}</div>;
}
export function ScenarioLayoutEditor({config,edit}:EditorProps){const layout=buildLayout(config);
 return <div><p className="scenario-help">u/v are world coordinates in the fixed isometric plane. Empty overrides use automatic campus placement and routing.</p>
 <h3>Services</h3>{config.topology.services.map(service=>{const placement=layout.buildings[service.id];return <section key={service.id}><h4>{service.name} · {config.layout.services[service.id]?'Manual':'Automatic'}</h4>{(['u','v'] as const).map(axis=><Field key={axis} label={`${service.id} world ${axis}`} value={placement[axis]} onChange={value=>edit(draft=>{moveCampus(draft,service.id,axis==='u'?Number(value):placement.u,axis==='v'?Number(value):placement.v);})}/>)}<button onClick={()=>edit(draft=>{delete draft.layout.services[service.id];})}>Automatic service placement</button></section>;})}
 <h3>Terminals</h3>{layout.terminals.map(terminal=>{const placement=config.layout.terminals[terminal.id]??{};return <section key={terminal.id}><h4>{terminal.name} · {config.layout.terminals[terminal.id]?'Manual':'Automatic'}</h4>{(['u','v'] as const).map(axis=><Field key={axis} label={`${terminal.id} world ${axis}`} value={terminal[axis]} onChange={value=>edit(draft=>{draft.layout.terminals[terminal.id]={...placement,[axis]:Number(value)};})}/>)}<Choice label={`${terminal.id} campus side`} value={placement.side??(terminal.producer?'east':'south')} options={['north','south','east','west'].map(id=>({id,name:id}))} onChange={value=>edit(draft=>{draft.layout.terminals[terminal.id]={wall:terminal.wall,side:value as 'north'|'south'|'east'|'west',offset:placement.offset??.5};})}/><Field label={`${terminal.id} side offset`} value={placement.offset??.5} onChange={value=>edit(draft=>{draft.layout.terminals[terminal.id]={wall:terminal.wall,side:placement.side??(terminal.producer?'east':'south'),offset:Number(value)};})}/><Choice label={`${terminal.id} bay wall`} value={terminal.wall} options={[{id:'front',name:'Front wall'},{id:'side',name:'Side wall'}]} onChange={value=>edit(draft=>{draft.layout.terminals[terminal.id]={...placement,wall:value as 'front'|'side'};})}/><button onClick={()=>edit(draft=>{delete draft.layout.terminals[terminal.id];})}>Automatic terminal placement</button></section>;})}
 <h3>Topic trunks and branches</h3>{config.topology.topics.map(topic=><section key={topic.id}><h4>{topic.name}</h4><Waypoints label={`${topic.id} trunk waypoints`} value={config.layout.topics[topic.id]?.waypoints} onChange={points=>edit(draft=>{draft.layout.topics[topic.id]??={};if(points)draft.layout.topics[topic.id].waypoints=points;else delete draft.layout.topics[topic.id].waypoints;for(const [key] of Object.entries(draft.layout.routes)){const producerId=key.split('/')[0];if(draft.topology.producers.some(producer=>producer.id===producerId&&producer.topicId===topic.id))delete draft.layout.routes[key];}})}/>{config.topology.consumerGroups.filter(group=>group.topicIds.includes(topic.id)).map(group=><Waypoints key={group.id} label={`${topic.id} branch to ${group.name}`} value={config.layout.topics[topic.id]?.branches?.[group.id]} onChange={points=>edit(draft=>{draft.layout.topics[topic.id]??={};draft.layout.topics[topic.id].branches??={};if(points)draft.layout.topics[topic.id].branches![group.id]=points;else delete draft.layout.topics[topic.id].branches![group.id];for(const key of Object.keys(draft.layout.routes))if(key.endsWith('/'+group.id))delete draft.layout.routes[key];})}/>)}</section>)}
 <h3>Existing route overrides</h3>{Object.entries(config.layout.routes).map(([id,route])=><section key={id}><Waypoints label={`${id} waypoints`} value={route.waypoints} onChange={points=>edit(draft=>{if(points)draft.layout.routes[id]={...route,waypoints:points};else delete draft.layout.routes[id];})}/></section>)}
 <h3>Overpasses</h3>{config.layout.overpasses.map(bridge=><section key={bridge.id}><h4>{bridge.id}</h4><Choice label={`${bridge.id} topic`} value={bridge.topic} options={config.topology.topics} onChange={value=>edit(draft=>{draft.layout.overpasses.find(item=>item.id===bridge.id)!.topic=value;})}/><label>Direction<select value={bridge.axis??'v'} onChange={event=>edit(draft=>{const item=draft.layout.overpasses.find(item=>item.id===bridge.id)!;item.axis=event.target.value as 'u'|'v';if(item.axis==='u')item.u=item.start+item.ramp+item.deck/2;else item.v=item.start+item.ramp+item.deck/2;})}><option value="v">V axis</option><option value="u">U axis</option></select></label>{([bridge.axis==='u'?'v':'u','start','ramp','deck','height'] as const).map(field=><Field key={field} label={`${bridge.id} ${field}`} value={bridge[field]} onChange={value=>edit(draft=>{const item=draft.layout.overpasses.find(item=>item.id===bridge.id)!;item[field]=Number(value);if(item.axis==='u')item.u=item.start+item.ramp+item.deck/2;else item.v=item.start+item.ramp+item.deck/2;})}/>)}<button onClick={()=>edit(draft=>{draft.layout.overpasses=draft.layout.overpasses.filter(item=>item.id!==bridge.id);})}>Remove overpass</button></section>)}<button disabled={!config.topology.topics.length} onClick={()=>edit(draft=>{let index=1;while(draft.layout.overpasses.some(bridge=>bridge.id===`bridge-${index}`))index++;draft.layout.overpasses.push({id:`bridge-${index}`,topic:draft.topology.topics[0].id,u:745,v:700,start:620,ramp:55,deck:50,height:48});})}>Add overpass</button>
 <button onClick={()=>edit(draft=>{draft.layout={services:{},terminals:{},topics:{},routes:{},overpasses:[]};})}>Automatic layout for entire scenario</button>
 </div>;
}
