import type {ScenarioConfig} from './scenarioTypes';
import {buildLayout} from './scenarioLayout';
export function newId(prefix:string,ids:string[]){let number=1;while(ids.includes(`${prefix}-${number}`))number++;return `${prefix}-${number}`;}
export function addService(config:ScenarioConfig,name='New service'){const id=newId('service',config.topology.services.map(item=>item.id));config.topology.services.push({id,name});return id;}
export function addTopic(config:ScenarioConfig,name='New topic'){const id=newId('topic',config.topology.topics.map(item=>item.id));config.topology.topics.push({id,name,partitionCount:4});config.state.topics[id]={messagesPerSecond:1000};config.visualization.topicColors[id]='#d78559';return id;}
export function connectProducer(config:ScenarioConfig,serviceId:string,topicId:string,count=1){if(config.topology.producers.some(item=>item.serviceId===serviceId&&item.topicId===topicId))throw new Error('This service already produces the topic. Edit its producer count.');const id=newId('producer',[...config.topology.producers,...config.topology.consumerGroups].map(item=>item.id));config.topology.producers.push({id,serviceId,topicId,producerCount:count});return id;}
export function addGroup(config:ScenarioConfig,serviceId:string,topicId:string,name='New group'){const id=newId('group',[...config.topology.producers,...config.topology.consumerGroups].map(item=>item.id));config.topology.consumerGroups.push({id,name,serviceId,topicIds:[topicId],consumerCount:2});config.state.consumerGroups[id]={consumptionRate:1000,lag:0};return id;}
export function duplicateGroup(config:ScenarioConfig,id:string,serviceId?:string){const original=config.topology.consumerGroups.find(item=>item.id===id);if(!original)throw new Error('Consumer group no longer exists');const copy=structuredClone(original),next=newId('group',[...config.topology.producers,...config.topology.consumerGroups].map(item=>item.id));copy.id=next;copy.name+=' copy';copy.serviceId=serviceId??copy.serviceId;config.topology.consumerGroups.push(copy);config.state.consumerGroups[next]=structuredClone(config.state.consumerGroups[id]);return next;}
export function duplicateService(config:ScenarioConfig,id:string){const original=config.topology.services.find(item=>item.id===id);if(!original)throw new Error('Service no longer exists');const next=addService(config,original.name+' copy');if(config.visualization.serviceStyles[id])config.visualization.serviceStyles[next]=structuredClone(config.visualization.serviceStyles[id]);for(const producer of config.topology.producers.filter(item=>item.serviceId===id))connectProducer(config,next,producer.topicId,producer.producerCount);for(const group of config.topology.consumerGroups.filter(item=>item.serviceId===id))duplicateGroup(config,group.id,next);return next;}
export function duplicateTopic(config:ScenarioConfig,id:string){const original=config.topology.topics.find(item=>item.id===id);if(!original)throw new Error('Topic no longer exists');const next=addTopic(config,original.name+' copy');config.topology.topics.find(item=>item.id===next)!.partitionCount=original.partitionCount;config.state.topics[next]=structuredClone(config.state.topics[id]);if(config.visualization.topicColors[id])config.visualization.topicColors[next]=config.visualization.topicColors[id];for(const producer of config.topology.producers.filter(item=>item.topicId===id))connectProducer(config,producer.serviceId,next,producer.producerCount);for(const group of config.topology.consumerGroups)if(group.topicIds.includes(id))group.topicIds.push(next);return next;}
export function moveCampus(config:ScenarioConfig,id:string,u:number,v:number){const previous=buildLayout(config).buildings[id];if(!previous)throw new Error('Cannot move an unknown service');const du=u-previous.u,dv=v-previous.v;config.layout.services[id]={...previous,u,v};const owned=[...config.topology.producers,...config.topology.consumerGroups].filter(item=>item.serviceId===id);for(const terminal of owned){const placement=config.layout.terminals[terminal.id];if(placement?.u!==undefined)placement.u+=du;if(placement?.v!==undefined)placement.v+=dv;}
 const topics=new Set([...config.topology.producers.filter(item=>item.serviceId===id).map(item=>item.topicId),...config.topology.consumerGroups.filter(item=>item.serviceId===id).flatMap(item=>item.topicIds)]);for(const key of Object.keys(config.layout.routes)){const producer=config.topology.producers.find(item=>item.id===key.split('/')[0]);if(producer&&topics.has(producer.topicId))delete config.layout.routes[key];}for(const topic of topics)delete config.layout.topics[topic];config.layout.overpasses=config.layout.overpasses.filter(bridge=>!topics.has(bridge.topic));delete config.layout.terrainOutline;delete config.layout.worldBounds;
}
