import {services,topics,storageSelection,type Selection} from './model';
import {ClusterInspector} from './ClusterInspector';
import {currentScenario} from './scenarioRuntime';
import {consumerGroups,groupById,producerById,partitionLoads} from './kafkaTopology';
export function SelectionPanel({selection,onClose}:{selection:Selection|null;onClose:()=>void}) {
 if(!selection)return null;
 if(storageSelection(selection))return <ClusterInspector configuration={currentScenario} selection={selection} onSelect={onClose}/>;
 if(selection.kind==='terminal'){
 const connection=selection.producer?producerById(selection.id):groupById(selection.id);
 return <aside aria-label="Selection details"><button className="close" onClick={onClose} aria-label="Close selection">×</button><small>{selection.producer?'PRODUCER TERMINAL':'CONSUMER GROUP'}</small><h2 style={{overflowWrap:'anywhere'}}>{'name' in connection?connection.name:connection.id}</h2><p>Service: {selection.name}</p><p>Topics: {'topic' in connection?connection.topic:connection.topics.join(', ')}</p><p>Active bays: {connection.instances}</p>{'lag' in connection&&<><p>Lag: {connection.lag.toLocaleString()}</p><p>Incoming: {connection.incomingRate.toLocaleString()} msg/s</p><p>Consumption: {connection.consumptionRate.toLocaleString()} msg/s</p><p className="status">{connection.status} - {connection.waiting} visible queued batches</p></>}<footer>Simulated consumer-group state · each vehicle represents a batch.</footer></aside>;
 }
 return <aside aria-label="Selection details"><button className="close" onClick={onClose} aria-label="Close selection">×</button><small>{selection.kind.toUpperCase()}</small><h2>{(selection.kind==='topic'?topics[selection.name].name:services[selection.name].name).toUpperCase()}{selection.kind==='service'?' SERVICE':''}</h2>
 {selection.kind==='topic'?<><p className="status">● Healthy topic</p><dl><dt>Partitions / physical lanes</dt><dd>{topics[selection.name].partitions}</dd><dt>Messages / second</dt><dd>{topics[selection.name].messagesPerSecond.toLocaleString()}</dd><dt>Producer instances</dt><dd>{topics[selection.name].producers}</dd><dt>Consumer groups</dt><dd>{topics[selection.name].groups}</dd></dl>{consumerGroups.filter(group=>group.topics.includes(selection.name)).map(group=><p key={group.id}>{group.id}<strong>{group.lag.toLocaleString()} lag</strong></p>)}</>:selection.kind==='service'?<><p>Consumes: {services[selection.name].consumes.join(', ')||'None'}</p><p>Produces: {services[selection.name].produces.join(', ')||'None'}</p><p>Producer gates: {services[selection.name].producers}</p><p>Consumer instances: {services[selection.name].consumers}</p>{consumerGroups.filter(group=>group.service===selection.name).map(group=><p key={group.id}>Group: {group.id}</p>)}</>:<><p>{selection.producer?'Producer · outgoing loading bay':'Consumer · incoming receiving bay'}</p><p>Topic: {selection.topic}</p><p>Instances: {selection.producer?services[selection.name].producers:services[selection.name].consumers}</p>{!selection.producer&&<p>Lag: {services[selection.name].lag.toLocaleString()}</p>}</>}
 <footer>Simulated data · vehicles represent batches of messages.</footer></aside>;
}
