import {useEffect,useState} from 'react';
import {Field,Choice,cleanReferences,type EditorProps} from './ScenarioFields';
import {addService,duplicateService} from './scenarioActions';
import {automaticColor} from './scenarioEncoding';
import {serviceRole} from './autoLayout';
import {ProducerForm} from './ProducerForm';
import {LabelSettings} from './LabelSettings';
export function ServiceSettings({config,edit,selectedId,onGroup,onTopic}:{selectedId:string;onGroup:(service:string)=>void;onTopic:(service:string)=>void}&EditorProps){const [id,setId]=useState(selectedId),[search,setSearch]=useState('');useEffect(()=>{setId(selectedId);},[selectedId]);const service=config.topology.services.find(item=>item.id===id);
 return <div><h3>Services</h3><input aria-label="Search services" placeholder="Search services" value={search} onChange={event=>setSearch(event.target.value)}/>{!config.topology.services.length&&<p>No services yet. Add a service to start your city.</p>}<div className="object-list">{config.topology.services.filter(item=>item.name.toLowerCase().includes(search.toLowerCase())).map(item=><button className={item.id===id?'chosen':''} key={item.id} onClick={()=>setId(item.id)}><i style={{background:config.visualization.serviceStyles[item.id]?.color??automaticColor(item.id)}}/><strong>{item.name}</strong><small>{new Set(config.topology.producers.filter(p=>p.serviceId===item.id).map(p=>p.topicId)).size} produced topics · {config.topology.consumerGroups.filter(g=>g.serviceId===item.id).length} groups</small></button>)}</div><button onClick={()=>edit(draft=>{setId(addService(draft));})}>Add service</button>
 {service&&<section><h3>{service.name}</h3><small>{serviceRole(config.topology,id)} service</small><Field label="Service name" type="text" value={service.name} onChange={value=>edit(draft=>{draft.topology.services.find(item=>item.id===id)!.name=value;})}/><Field label="Service color" type="color" value={config.visualization.serviceStyles[id]?.color??automaticColor(id)} onChange={value=>edit(draft=>{draft.visualization.serviceStyles[id]={...draft.visualization.serviceStyles[id],color:value};delete draft.visualization.serviceStyles[id].palette;})}/><button onClick={()=>edit(draft=>{setId(duplicateService(draft,id));})}>Duplicate service</button><button onClick={()=>edit(draft=>{draft.topology.services=draft.topology.services.filter(item=>item.id!==id);cleanReferences(draft);setId('');})}>Delete service</button><h4>Kafka participation</h4><button disabled={!config.topology.topics.length} onClick={()=>onGroup(id)}>Add consumer group</button><button onClick={()=>onTopic(id)}>Add produced topic</button>
 {config.topology.topics.length>0&&<ProducerForm key={id} config={config} edit={edit} serviceId={id}/>}
 {config.topology.producers.filter(item=>item.serviceId===id).map(producer=><Field key={producer.id} label={`${config.topology.topics.find(topic=>topic.id===producer.topicId)!.name} producer count`} value={producer.producerCount} onChange={value=>edit(draft=>{draft.topology.producers.find(item=>item.id===producer.id)!.producerCount=Number(value);})}/>)}
 <details><summary>Advanced service settings</summary><Choice label="Building personality" value={config.visualization.serviceStyles[id]?.art??'Office'} options={['Office','Orders','Payment','Analytics','Notification'].map(value=>({id:value,name:value}))} onChange={value=>edit(draft=>{draft.visualization.serviceStyles[id]={color:config.visualization.serviceStyles[id]?.color??automaticColor(id),art:value as 'Office'};})}/><LabelSettings kind="service" id={id} config={config} edit={edit}/></details></section>}
 </div>;
}
