import {useEffect,useState} from 'react';
import {Field,cleanReferences,type EditorProps} from './ScenarioFields';
import {addTopic,duplicateTopic} from './scenarioActions';
import {automaticColor} from './scenarioEncoding';
import {ProducerForm} from './ProducerForm';
import {ScenarioStateEditor} from './ScenarioStateEditor';
import {LabelSettings} from './LabelSettings';
export function TopicSettings({config,edit,focused=false,selectedId,producerService,onGroup}:{focused?:boolean;selectedId:string;producerService?:string;onGroup:(topic:string)=>void}&EditorProps){const [id,setId]=useState(selectedId),[search,setSearch]=useState('');useEffect(()=>{setId(selectedId);},[selectedId]);const topic=config.topology.topics.find(item=>item.id===id);
 return <div><h3>Topics</h3>{!focused&&<><input aria-label="Search topics" placeholder="Search topics" value={search} onChange={event=>setSearch(event.target.value)}/>{!config.topology.topics.length&&<p>No topics yet. Add a topic, then connect its producer.</p>}<div className="object-list">{config.topology.topics.filter(item=>item.name.toLowerCase().includes(search.toLowerCase())).map(item=><button key={item.id} className={id===item.id?'chosen':''} onClick={()=>setId(item.id)}><i style={{background:config.visualization.topicColors[item.id]??automaticColor(item.id)}}/><strong>{item.name}</strong><small>{item.partitionCount} lanes · {config.state.topics[item.id].messagesPerSecond.toLocaleString()} msg/s · {new Set(config.topology.producers.filter(p=>p.topicId===item.id).map(p=>p.serviceId)).size} producers · {config.topology.consumerGroups.filter(g=>g.topicIds.includes(item.id)).length} groups</small></button>)}</div><button onClick={()=>edit(draft=>{setId(addTopic(draft));})}>Add topic</button>
 </>}{topic&&<section><h3>{topic.name}</h3><Field label="Topic name" type="text" value={topic.name} onChange={value=>edit(draft=>{draft.topology.topics.find(item=>item.id===id)!.name=value;})}/><Field label="Partition count" value={topic.partitionCount} onChange={value=>edit(draft=>{draft.topology.topics.find(item=>item.id===id)!.partitionCount=Number(value);})}/><Field label="Topic messages/sec" value={config.state.topics[id].messagesPerSecond} onChange={value=>edit(draft=>{draft.state.topics[id].messagesPerSecond=Number(value);})}/><Field label="Topic color" type="color" value={config.visualization.topicColors[id]??automaticColor(id)} onChange={value=>edit(draft=>{draft.visualization.topicColors[id]=value;})}/><button onClick={()=>edit(draft=>{setId(duplicateTopic(draft,id));})}>Duplicate topic</button><button onClick={()=>edit(draft=>{draft.topology.topics=draft.topology.topics.filter(item=>item.id!==id);cleanReferences(draft);setId('');})}>Delete topic</button>
 <ProducerForm key={`${id}/${producerService}`} config={config} edit={edit} serviceId={producerService} topicId={id}/>{config.topology.producers.filter(item=>item.topicId===id).map(producer=><div key={producer.id}><Field label={`${config.topology.services.find(service=>service.id===producer.serviceId)!.name} producer count`} value={producer.producerCount} onChange={value=>edit(draft=>{draft.topology.producers.find(item=>item.id===producer.id)!.producerCount=Number(value);})}/><button onClick={()=>edit(draft=>{draft.topology.producers=draft.topology.producers.filter(item=>item.id!==producer.id);cleanReferences(draft);})}>Disconnect producer</button></div>)}<button disabled={!config.topology.services.length} onClick={()=>onGroup(id)}>Add consumer group for topic</button>
 <details><summary>Advanced partition distribution</summary><ScenarioStateEditor config={{...config,topology:{...config.topology,topics:[topic],producers:[],consumerGroups:[]}}} edit={edit}/></details><LabelSettings kind="topic" id={id} config={config} edit={edit}/></section>}
 </div>;
}
