import {Field,type EditorProps} from './ScenarioFields';
import {VehiclePreview,VehicleGallery} from './VehiclePreview';
import {automaticColor} from './scenarioEncoding';
export function VisualSettings({config,edit}:EditorProps){const visual=config.visualization,first=config.topology.topics[0],accent=first?visual.topicColors[first.id]??automaticColor(first.id):'#d78559',labels=visual.labels??{serviceSize:14,topicSize:11,poleLength:32,offsetX:0,offsetY:0};
 return <div><h3>Vehicles</h3><p className="scenario-help">Shape shows message volume. Trim color identifies the topic. Previews use the world's sprite renderer and update with your draft.</p><VehicleGallery maxTrailers={visual.maxTrailers} accent={accent}/>
 {(['car','van','truck','semi'] as const).map((kind,index)=>{const lower=index?visual.thresholds[(['car','van','truck'] as const)[index-1]]+1:0;return <section key={kind}><VehiclePreview kind={kind} accent={accent}/><h4>{kind==='truck'?'Box truck':kind==='semi'?'Semi':kind==='car'?'Car':'Van'}</h4><Field label={`${kind} messages represented`} value={visual.vehicles[kind].messagesPerVehicle} onChange={value=>edit(draft=>{draft.visualization.vehicles[kind].messagesPerVehicle=Number(value);})}/><p>Rate range: {lower.toLocaleString()} to {visual.thresholds[kind].toLocaleString()} msg/s per partition</p><Field label={`${kind} upper rate threshold`} value={visual.thresholds[kind]} onChange={value=>edit(draft=>{draft.visualization.thresholds[kind]=Number(value);})}/></section>;})}
 <section><h4>Extra trailers</h4><VehiclePreview kind="semi" trailers={Math.max(1,Math.min(8,visual.maxTrailers))} accent={accent}/><Field label="Maximum trailers including first" value={visual.maxTrailers} onChange={value=>edit(draft=>{draft.visualization.maxTrailers=Number(value);})}/><Field label="Messages per extra trailer" value={visual.vehicles.trailer.messagesPerTrailer} onChange={value=>edit(draft=>{draft.visualization.vehicles.trailer.messagesPerTrailer=Number(value);})}/></section>
 <h3>Topic colors</h3>{config.topology.topics.map(topic=>{const color=visual.topicColors[topic.id]??automaticColor(topic.id);return <section key={topic.id}><h4>{topic.name}</h4><div className="road-accent-preview" style={{borderColor:color}}/><VehiclePreview kind="truck" accent={color}/><Field label={`${topic.name} topic color`} type="color" value={color} onChange={value=>edit(draft=>{draft.visualization.topicColors[topic.id]=value;})}/></section>;})}
 <h3>Road style</h3><p className="scenario-help">Neutral asphalt with topic-colored edges. Partition counts control lane width; related roads share a trunk.</p>
 <h3>Queue style</h3><Field label="Messages per waiting vehicle" value={visual.messagesPerQueueVehicle} onChange={value=>edit(draft=>{draft.visualization.messagesPerQueueVehicle=Number(value);})}/><Field label="Maximum queue vehicles" value={visual.maxQueueVehicles} onChange={value=>edit(draft=>{draft.visualization.maxQueueVehicles=Number(value);})}/>
 <h3>Labels</h3>{(['serviceSize','topicSize','poleLength','offsetX','offsetY'] as const).map(field=><Field key={field} label={{serviceSize:'Service label size',topicSize:'Topic label size',poleLength:'Road sign pole length',offsetX:'Default label horizontal offset',offsetY:'Default label vertical offset'}[field]} value={labels[field]} onChange={value=>edit(draft=>{draft.visualization.labels={...labels,[field]:Number(value)};})}/>)}
 <details><summary>Advanced traffic limits</summary>{(['maxVehiclesPerLane','maxVehiclesPerTopic','maxVehiclesTotal','trafficWindowSeconds'] as const).map(field=><Field key={field} label={field} value={visual[field]} onChange={value=>edit(draft=>{draft.visualization[field]=Number(value);})}/>)}</details></div>;
}
